# This is a workflow for generating Snake Game on Contribution field

name: contribution-snake-game

on:
  # run automatically every 6 hours
  schedule:
    - cron: "* */1 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate-snake-game-from-github-contribution-grid
        uses: actions/checkout@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            banners/github-contribution-grid-snake.svg
            banners/github-contribution-grid-snake-dark.svg?palette=github-dark
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: assets
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
